@extends('dbclient::layout')

@section('title', 'Table: ' . $table)

@section('content')
<div class="card">
  <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; flex-wrap: wrap; gap: 15px;">
    <div>
      <h2>Table: <strong>{{ $table }}</strong></h2>
      <p style="color: #6b7280; margin-top: 5px;">
        Total Rows: <span class="badge badge-primary" id="totalRows">{{ number_format($rowCount) }}</span>
        | Columns: <span class="badge badge-success">{{ count($columns) }}</span>
      </p>
    </div>
    <div style="display: flex; gap: 10px; align-items: center;">
      <button class="btn btn-success" id="addRowBtn" onclick="openAddModal()" style="display: none;">+ Add Row</button>
      <a href="{{ route('dbclient.tables') }}{{ request()->has('page') || request()->has('per_page') ? '?' . http_build_query(request()->only(['page', 'per_page'])) : '' }}" class="btn btn-secondary" style="text-decoration: none; display: inline-flex; align-items: center; gap: 5px;">
        <span>←</span> Back to Tables
      </a>
    </div>
  </div>

  <!-- Tabs Navigation -->
  <div class="tabs">
    <button class="tab-btn active" onclick="switchTab('data', this)">Table Data</button>
    <button class="tab-btn" onclick="switchTab('structure', this)">Table Structure</button>
  </div>

  <!-- Tab Content: Table Data -->
  <div id="tab-data" class="tab-content active">
    <!-- Search and Controls -->
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; flex-wrap: wrap; gap: 15px; padding: 15px; background: #f9fafb; border-radius: 8px;">
      <div style="flex: 1; min-width: 250px;">
        <div style="position: relative;">
          <input type="text"
            id="searchInput"
            class="form-control"
            placeholder="Search in all columns..."
            style="padding-left: 40px;">
          <span style="position: absolute; left: 12px; top: 50%; transform: translateY(-50%); color: #6b7280;">🔍</span>
        </div>
      </div>
      <div style="display: flex; align-items: center; gap: 10px;">
        <label style="color: #6b7280; font-size: 14px;">Per Page:</label>
        <select id="perPageSelect" class="form-control" style="width: auto; min-width: 80px;">
          <option value="10">10</option>
          <option value="20" selected>20</option>
          <option value="50">50</option>
          <option value="100">100</option>
        </select>
      </div>
    </div>

    <!-- Loading Indicator -->
    <div id="loadingIndicator" style="text-align: center; padding: 40px; display: none;">
      <div style="display: inline-block; width: 40px; height: 40px; border: 4px solid #e5e7eb; border-top-color: #2563eb; border-radius: 50%; animation: spin 1s linear infinite;"></div>
      <p style="margin-top: 15px; color: #6b7280;">Loading data...</p>
    </div>

    <!-- Data Table -->
    <div id="tableContainer" style="overflow-x: auto;">
      <table class="table" id="dataTable">
        <thead>
          <tr>
            <th style="width: 150px;">Actions</th>
            @php
            // Reorder columns: primary key first, then others
            $orderedColumns = [];
            if ($primaryKey && isset($columns[$primaryKey])) {
            $orderedColumns[$primaryKey] = $columns[$primaryKey];
            foreach ($columns as $col => $type) {
            if ($col !== $primaryKey) {
            $orderedColumns[$col] = $type;
            }
            }
            } else {
            $orderedColumns = $columns;
            }
            @endphp
            @foreach($orderedColumns as $column => $type)
            <th>{{ $column }}</th>
            @endforeach
          </tr>
        </thead>
        <tbody id="tableBody">
          <tr>
            <td colspan="{{ count($columns) + 1 }}" style="text-align: center; padding: 40px; color: #6b7280;">
              Loading data...
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div id="paginationContainer" style="display: none; margin-top: 20px;">
      <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 15px;">
        <div style="color: #6b7280; font-size: 14px;">
          Showing <strong id="showingFrom">0</strong> to <strong id="showingTo">0</strong> of <strong id="showingTotal">0</strong> entries
        </div>
        <div class="pagination" id="pagination">
          <!-- Pagination will be generated by JavaScript -->
        </div>
      </div>
    </div>
  </div>

  <!-- Tab Content: Table Structure -->
  <div id="tab-structure" class="tab-content">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
      <h3 style="margin: 0;">Table Structure</h3>
      <button class="btn btn-success btn-sm" onclick="openAddColumnModal()">+ Add Column</button>
    </div>

    <div style="overflow-x: auto;">
      <table class="table">
        <thead>
          <tr>
            <th>Field</th>
            <th>Type</th>
            <th>Null</th>
            <th>Key</th>
            <th>Default</th>
            <th>Extra</th>
            <th style="width: 150px;">Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach($structure as $col)
          <tr>
            <td><strong>{{ $col['field'] }}</strong></td>
            <td>{{ $col['type'] }}</td>
            <td>{{ $col['null'] }}</td>
            <td>{{ $col['key'] }}</td>
            <td>{{ $col['default'] ?? 'NULL' }}</td>
            <td>{{ $col['extra'] }}</td>
            <td>
              <button class="btn btn-secondary btn-sm" onclick="editColumn('{{ $col['field'] }}', '{{ $col['type'] }}', '{{ $col['null'] }}', '{{ $col['default'] ?? '' }}')" style="margin-right: 5px;">Edit</button>
              @if($col['key'] !== 'PRI')
              <button class="btn btn-danger btn-sm" onclick="deleteColumn('{{ $col['field'] }}')">Delete</button>
              @else
              <span style="color: #9ca3af; font-size: 12px;">Primary Key</span>
              @endif
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Add/Edit Modal -->
<div id="rowModal" class="modal">
  <div class="modal-content" style="max-width: 700px;">
    <div class="modal-header">
      <h3 id="modalTitle">Add Row</h3>
      <span class="close" onclick="closeModal()">&times;</span>
    </div>
    <form id="rowForm">
      <input type="hidden" id="rowId" name="id">
      <div style="max-height: 60vh; overflow-y: auto; padding-right: 10px;">
        @foreach($columns as $column => $type)
        <div class="form-group">
          <label for="field_{{ str_replace(['-', '.'], '_', $column) }}">{{ $column }} <small>({{ $type }})</small></label>
          <input type="text"
            class="form-control"
            id="field_{{ str_replace(['-', '.'], '_', $column) }}"
            name="{{ $column }}"
            placeholder="Enter {{ $column }}">
        </div>
        @endforeach
      </div>
      <div style="display: flex; gap: 10px; justify-content: flex-end; margin-top: 20px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
        <button type="button" class="btn btn-secondary" onclick="closeModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
  </div>
</div>

<!-- Delete Confirmation Modal -->
<div id="deleteConfirmModal" class="modal">
  <div class="modal-content" style="max-width: 500px;">
    <div class="modal-header">
      <h3 id="deleteModalTitle">Confirm Deletion</h3>
      <span class="close" onclick="closeDeleteModal()">&times;</span>
    </div>
    <div style="padding: 20px 0;">
      <p style="color: #6b7280; margin-bottom: 15px; font-size: 15px;" id="deleteModalMessage">
        This action cannot be undone. Please type <strong style="color: #dc2626;">DELETE</strong> to confirm.
      </p>
      <div class="form-group">
        <label for="deleteConfirmInput">Type <strong style="color: #dc2626;">DELETE</strong> to confirm:</label>
        <input
          type="text"
          id="deleteConfirmInput"
          class="form-control"
          placeholder="Type DELETE here"
          autocomplete="off"
          style="text-transform: uppercase; font-weight: 600; letter-spacing: 1px;">
        <small id="deleteConfirmHint" style="color: #6b7280; margin-top: 5px; display: block;">
          You must type exactly "DELETE" to proceed
        </small>
      </div>
      <div style="display: flex; gap: 10px; justify-content: flex-end; margin-top: 20px;">
        <button type="button" class="btn btn-secondary" onclick="closeDeleteModal()">Cancel</button>
        <button type="button" id="confirmDeleteBtn" class="btn btn-danger" onclick="executeDelete()" disabled>
          Delete
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Add/Edit Column Modal -->
<div id="columnModal" class="modal">
  <div class="modal-content" style="max-width: 600px;">
    <div class="modal-header">
      <h3 id="columnModalTitle">Add Column</h3>
      <span class="close" onclick="closeColumnModal()">&times;</span>
    </div>
    <form id="columnForm">
      <input type="hidden" id="columnNameOriginal" name="column_name_original">
      <div class="form-group">
        <label for="columnName">Column Name <span style="color: #dc2626;">*</span></label>
        <input type="text" class="form-control" id="columnName" name="column_name" required placeholder="e.g., email, status">
      </div>
      <div class="form-group">
        <label for="columnType">Column Type <span style="color: #dc2626;">*</span></label>
        <select class="form-control" id="columnType" name="column_type" required>
          <option value="">Select type...</option>
          <optgroup label="String Types">
            <option value="VARCHAR(255)">VARCHAR(255)</option>
            <option value="VARCHAR(100)">VARCHAR(100)</option>
            <option value="VARCHAR(500)">VARCHAR(500)</option>
            <option value="TEXT">TEXT</option>
            <option value="LONGTEXT">LONGTEXT</option>
            <option value="CHAR(255)">CHAR(255)</option>
          </optgroup>
          <optgroup label="Numeric Types">
            <option value="INT">INT</option>
            <option value="BIGINT">BIGINT</option>
            <option value="TINYINT">TINYINT</option>
            <option value="DECIMAL(10,2)">DECIMAL(10,2)</option>
            <option value="FLOAT">FLOAT</option>
            <option value="DOUBLE">DOUBLE</option>
          </optgroup>
          <optgroup label="Date/Time Types">
            <option value="DATE">DATE</option>
            <option value="DATETIME">DATETIME</option>
            <option value="TIMESTAMP">TIMESTAMP</option>
            <option value="TIME">TIME</option>
          </optgroup>
          <optgroup label="Other Types">
            <option value="BOOLEAN">BOOLEAN</option>
            <option value="JSON">JSON</option>
            <option value="BLOB">BLOB</option>
          </optgroup>
        </select>
        <small style="color: #6b7280; margin-top: 5px; display: block;">Or enter custom type (e.g., ENUM('value1','value2'))</small>
        <input type="text" class="form-control" id="columnTypeCustom" name="column_type_custom" style="margin-top: 5px;" placeholder="Custom type...">
      </div>
      <div class="form-group">
        <label>
          <input type="checkbox" id="columnNullable" name="nullable" checked> Allow NULL values
        </label>
      </div>
      <div class="form-group">
        <label for="columnDefault">Default Value</label>
        <input type="text" class="form-control" id="columnDefault" name="default_value" placeholder="Leave empty for no default">
        <small style="color: #6b7280; margin-top: 5px; display: block;">For NULL default, leave empty and uncheck nullable</small>
      </div>
      <div class="form-group" id="afterColumnGroup" style="display: none;">
        <label for="afterColumn">Add After Column</label>
        <select class="form-control" id="afterColumn" name="after_column">
          <option value="">Add at end</option>
          @foreach($structure as $col)
          <option value="{{ $col['field'] }}">{{ $col['field'] }}</option>
          @endforeach
        </select>
      </div>
      <div style="display: flex; gap: 10px; justify-content: flex-end; margin-top: 20px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
        <button type="button" class="btn btn-secondary" onclick="closeColumnModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
  </div>
</div>
@endsection

@push('styles')
<style>
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .table-container {
    position: relative;
  }

  #dataTable {
    background: white;
  }

  #dataTable th {
    background: #f9fafb;
    position: sticky;
    top: 0;
    z-index: 10;
    font-weight: 600;
  }

  #dataTable tbody tr:hover {
    background: #f9fafb;
  }

  .pagination {
    display: flex;
    gap: 5px;
    align-items: center;
  }

  .pagination a,
  .pagination span {
    padding: 8px 12px;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    text-decoration: none;
    color: #374151;
    min-width: 40px;
    text-align: center;
    transition: all 0.2s;
  }

  .pagination a:hover:not(.disabled) {
    background: #f3f4f6;
    border-color: #9ca3af;
  }

  .pagination .active {
    background: #2563eb;
    color: white;
    border-color: #2563eb;
  }

  .pagination .disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .btn-sm {
    padding: 6px 12px;
    font-size: 13px;
  }

  /* Tabs Styles */
  .tabs {
    display: flex;
    gap: 5px;
    border-bottom: 2px solid #e5e7eb;
    margin-bottom: 20px;
  }

  .tab-btn {
    padding: 12px 24px;
    background: transparent;
    border: none;
    border-bottom: 3px solid transparent;
    cursor: pointer;
    font-size: 14px;
    font-weight: 500;
    color: #6b7280;
    transition: all 0.2s;
    margin-bottom: -2px;
  }

  .tab-btn:hover {
    color: #2563eb;
    background: #f9fafb;
  }

  .tab-btn.active {
    color: #2563eb;
    border-bottom-color: #2563eb;
    background: transparent;
  }

  .tab-content {
    display: none;
  }

  .tab-content.active {
    display: block;
  }

  #deleteConfirmInput:focus {
    border-color: #dc2626;
    box-shadow: 0 0 0 3px rgba(220, 38, 38, 0.1);
  }

  #confirmDeleteBtn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  #confirmDeleteBtn:not(:disabled) {
    opacity: 1;
  }
</style>
@endpush

@push('scripts')
<script>
  const tableName = '{{ $table }}';
  @php
  // Reorder columns: primary key first, then others
  $orderedColumns = [];
  if ($primaryKey && isset($columns[$primaryKey])) {
    $orderedColumns[$primaryKey] = $columns[$primaryKey];
    foreach($columns as $col => $type) {
      if ($col !== $primaryKey) {
        $orderedColumns[$col] = $type;
      }
    }
  } else {
    $orderedColumns = $columns;
  }
  @endphp
  const columns = @json(array_keys($orderedColumns));
  const primaryKey = '{{ $primaryKey }}';
  let isEditMode = false;
  let currentPage = 1;
  let perPage = 20;
  let searchTerm = '';
  let searchTimeout;

  // Load table data
  function loadTableData(page = 1, search = '') {
    currentPage = page;
    searchTerm = search;

    $('#loadingIndicator').show();
    $('#tableContainer').hide();
    $('#paginationContainer').hide();

    $.ajax({
      url: '/dbclient/table/' + tableName + '/rows',
      type: 'GET',
      data: {
        page: page,
        per_page: perPage,
        search: search
      },
      success: function(response) {
        renderTable(response.data);
        renderPagination(response);
        updateStats(response);
        $('#loadingIndicator').hide();
        $('#tableContainer').show();
        $('#paginationContainer').show();
      },
      error: function(xhr) {
        $('#loadingIndicator').hide();
        $('#tableContainer').show();
        const error = xhr.responseJSON?.error || 'Failed to load data';
        $('#tableBody').html('<tr><td colspan="' + (columns.length + 1) + '" style="text-align: center; padding: 40px; color: #dc2626;">Error: ' + error + '</td></tr>');
      }
    });
  }

  // Render table rows
  function renderTable(data) {
    if (data.length === 0) {
      $('#tableBody').html('<tr><td colspan="' + (columns.length + 1) + '" style="text-align: center; padding: 40px; color: #6b7280;">No data found</td></tr>');
      return;
    }

    let html = '';
    data.forEach(function(row) {
      // Get primary key value first
      const rowId = row[primaryKey] !== undefined ? row[primaryKey] : (row.id !== undefined ? row.id : row[columns[0]]);
      const rowIdEscaped = typeof rowId === 'string' ? "'" + escapeHtml(rowId).replace(/'/g, "\\'") + "'" : rowId;

      html += '<tr>';

      // Actions column first
      html += '<td style="white-space: nowrap;">';
      html += '<button class="btn btn-secondary btn-sm" onclick="editRow(' + rowIdEscaped + ')" style="margin-right: 5px;">Edit</button>';
      html += '<button class="btn btn-info btn-sm" onclick="copyRow(' + rowIdEscaped + ')" style="margin-right: 5px; background-color: #0dcaf0; color: white;">Copy</button>';
      html += '<button class="btn btn-danger btn-sm" onclick="deleteRow(' + rowIdEscaped + ')">Delete</button>';
      html += '</td>';

      // Then data columns (already ordered: primary key first, then others)
      columns.forEach(function(column) {
        let value = row[column];
        if (value === null || value === undefined) {
          value = '<em style="color: #9ca3af;">NULL</em>';
        } else if (typeof value === 'string' && value.length > 50) {
          value = '<span title="' + escapeHtml(value) + '">' + escapeHtml(value.substring(0, 50)) + '...</span>';
        } else {
          value = escapeHtml(String(value));
        }
        html += '<td>' + value + '</td>';
      });

      html += '</tr>';
    });

    $('#tableBody').html(html);
  }

  // Render pagination
  function renderPagination(response) {
    if (response.last_page <= 1) {
      $('#paginationContainer').hide();
      return;
    }

    let html = '';
    const current = response.current_page;
    const last = response.last_page;

    // Helper function to escape JavaScript string
    function escapeJs(str) {
      return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');
    }

    const searchEscaped = escapeJs(searchTerm);

    // Previous button
    if (current > 1) {
      html += '<a href="#" onclick="loadTableData(' + (current - 1) + ', \'' + searchEscaped + '\'); return false;">&laquo; Prev</a>';
    } else {
      html += '<span class="disabled">&laquo; Prev</span>';
    }

    // Page numbers
    let start = Math.max(1, current - 2);
    let end = Math.min(last, current + 2);

    if (start > 1) {
      html += '<a href="#" onclick="loadTableData(1, \'' + searchEscaped + '\'); return false;">1</a>';
      if (start > 2) {
        html += '<span>...</span>';
      }
    }

    for (let i = start; i <= end; i++) {
      if (i === current) {
        html += '<span class="active">' + i + '</span>';
      } else {
        html += '<a href="#" onclick="loadTableData(' + i + ', \'' + searchEscaped + '\'); return false;">' + i + '</a>';
      }
    }

    if (end < last) {
      if (end < last - 1) {
        html += '<span>...</span>';
      }
      html += '<a href="#" onclick="loadTableData(' + last + ', \'' + searchEscaped + '\'); return false;">' + last + '</a>';
    }

    // Next button
    if (current < last) {
      html += '<a href="#" onclick="loadTableData(' + (current + 1) + ', \'' + searchEscaped + '\'); return false;">Next &raquo;</a>';
    } else {
      html += '<span class="disabled">Next &raquo;</span>';
    }

    $('#pagination').html(html);
  }

  // Update statistics
  function updateStats(response) {
    $('#showingFrom').text(response.from || 0);
    $('#showingTo').text(response.to || 0);
    $('#showingTotal').text(response.total || 0);
    $('#totalRows').text(response.total.toLocaleString());
  }

  // Escape HTML
  function escapeHtml(text) {
    const map = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return String(text).replace(/[&<>"']/g, function(m) {
      return map[m];
    });
  }

  // Search handler
  $('#searchInput').on('input', function() {
    clearTimeout(searchTimeout);
    const search = $(this).val();
    searchTimeout = setTimeout(function() {
      loadTableData(1, search);
    }, 500); // Debounce 500ms
  });

  // Per page change handler
  $('#perPageSelect').on('change', function() {
    perPage = $(this).val();
    loadTableData(1, searchTerm);
  });

  // Tab switching function
  function switchTab(tab, buttonElement) {
    // Hide all tab contents
    document.querySelectorAll('.tab-content').forEach(content => {
      content.classList.remove('active');
    });

    // Remove active class from all tab buttons
    document.querySelectorAll('.tab-btn').forEach(btn => {
      btn.classList.remove('active');
    });

    // Show selected tab content
    document.getElementById('tab-' + tab).classList.add('active');

    // Add active class to clicked tab button
    if (buttonElement) {
      buttonElement.classList.add('active');
    }

    // Show/hide Add Row button based on tab
    if (tab === 'data') {
      document.getElementById('addRowBtn').style.display = 'inline-block';
    } else {
      document.getElementById('addRowBtn').style.display = 'none';
    }
  }

  // Initial load
  $(document).ready(function() {
    loadTableData(1, '');
    // Show Add Row button on initial load (data tab is active by default)
    document.getElementById('addRowBtn').style.display = 'inline-block';
  });

  function openAddModal() {
    isEditMode = false;
    document.getElementById('modalTitle').textContent = 'Add Row';
    document.getElementById('rowForm').reset();
    document.getElementById('rowId').value = '';
    document.getElementById('rowModal').classList.add('active');
  }

  function editRow(id) {
    isEditMode = true;
    document.getElementById('modalTitle').textContent = 'Edit Row';
    document.getElementById('rowId').value = id;

    // Encode ID for URL
    const encodedId = encodeURIComponent(id);

    $.get('/dbclient/table/' + tableName + '/row/' + encodedId, function(response) {
      if (response.success) {
        const data = response.data;
        columns.forEach(function(column) {
          const fieldId = 'field_' + column.replace(/[^a-zA-Z0-9_]/g, '_');
          const fieldElement = document.getElementById(fieldId);
          if (fieldElement && data[column] !== undefined && data[column] !== null) {
            fieldElement.value = data[column];
          }
        });
        document.getElementById('rowModal').classList.add('active');
      }
    }).fail(function() {
      showToast({
        eleWrapper: '#dbclient-toaster',
        msg: 'Failed to load row data',
        theme: 'error',
        closeButton: true,
        autoClose: true
      });
    });
  }

  function copyRow(id) {
    isEditMode = false; // Set to false so it creates a new row
    document.getElementById('modalTitle').textContent = 'Copy Row';
    document.getElementById('rowId').value = ''; // Clear ID so it creates new row

    // Encode ID for URL
    const encodedId = encodeURIComponent(id);

    $.get('/dbclient/table/' + tableName + '/row/' + encodedId, function(response) {
      if (response.success) {
        const data = response.data;
        columns.forEach(function(column) {
          const fieldId = 'field_' + column.replace(/[^a-zA-Z0-9_]/g, '_');
          const fieldElement = document.getElementById(fieldId);
          if (fieldElement) {
            // Clear primary key field, keep other fields
            if (column === primaryKey) {
              fieldElement.value = '';
            } else if (data[column] !== undefined && data[column] !== null) {
              fieldElement.value = data[column];
            } else {
              fieldElement.value = '';
            }
          }
        });
        document.getElementById('rowModal').classList.add('active');
      }
    }).fail(function() {
      showToast({
        eleWrapper: '#dbclient-toaster',
        msg: 'Failed to load row data',
        theme: 'error',
        closeButton: true,
        autoClose: true
      });
    });
  }

  // Delete confirmation variables
  let pendingDeleteType = null; // 'row' or 'column'
  let pendingDeleteId = null;

  function deleteRow(id) {
    pendingDeleteType = 'row';
    pendingDeleteId = id;
    document.getElementById('deleteModalTitle').textContent = 'Delete Row';
    document.getElementById('deleteModalMessage').innerHTML =
      'Are you sure you want to delete this row? This action cannot be undone.<br><br>' +
      'Please type <strong style="color: #dc2626;">DELETE</strong> to confirm.';
    document.getElementById('deleteConfirmInput').value = '';
    document.getElementById('confirmDeleteBtn').disabled = true;
    document.getElementById('deleteConfirmInput').style.borderColor = '#d1d5db';
    document.getElementById('deleteConfirmHint').innerHTML = 'You must type exactly "DELETE" to proceed';
    document.getElementById('deleteConfirmModal').classList.add('active');
    document.getElementById('deleteConfirmInput').focus();
  }

  function deleteColumn(columnName) {
    pendingDeleteType = 'column';
    pendingDeleteId = columnName;
    document.getElementById('deleteModalTitle').textContent = 'Delete Column';
    document.getElementById('deleteModalMessage').innerHTML =
      'Are you sure you want to delete column <strong>"' + escapeHtml(columnName) + '"</strong>? This action cannot be undone.<br><br>' +
      'Please type <strong style="color: #dc2626;">DELETE</strong> to confirm.';
    document.getElementById('deleteConfirmInput').value = '';
    document.getElementById('confirmDeleteBtn').disabled = true;
    document.getElementById('deleteConfirmInput').style.borderColor = '#d1d5db';
    document.getElementById('deleteConfirmHint').innerHTML = 'You must type exactly "DELETE" to proceed';
    document.getElementById('deleteConfirmModal').classList.add('active');
    document.getElementById('deleteConfirmInput').focus();
  }

  function closeDeleteModal() {
    document.getElementById('deleteConfirmModal').classList.remove('active');
    document.getElementById('deleteConfirmInput').value = '';
    document.getElementById('confirmDeleteBtn').disabled = true;
    document.getElementById('deleteConfirmInput').style.borderColor = '#d1d5db';
    document.getElementById('deleteConfirmHint').innerHTML = 'You must type exactly "DELETE" to proceed';
    pendingDeleteType = null;
    pendingDeleteId = null;
  }

  function executeDelete() {
    if (pendingDeleteType === 'row') {
      const encodedId = encodeURIComponent(pendingDeleteId);

      $.ajax({
        url: '/dbclient/table/' + tableName + '/' + encodedId + '/delete',
        type: 'DELETE',
        success: function(response) {
          closeDeleteModal();
          if (response.success) {
            showToast({
              eleWrapper: '#dbclient-toaster',
              msg: response.message || 'Row deleted successfully',
              theme: 'success',
              closeButton: true,
              autoClose: true
            });
            loadTableData(currentPage, searchTerm);
          } else {
            showToast({
              eleWrapper: '#dbclient-toaster',
              msg: response.error || 'Failed to delete row',
              theme: 'error',
              closeButton: true,
              autoClose: true
            });
          }
        },
        error: function(xhr) {
          closeDeleteModal();
          const error = xhr.responseJSON?.error || 'Failed to delete row';
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: error,
            theme: 'error',
            closeButton: true,
            autoClose: true
          });
        }
      });
    } else if (pendingDeleteType === 'column') {
      $.ajax({
        url: '/dbclient/table/' + tableName + '/column/' + encodeURIComponent(pendingDeleteId) + '/delete',
        type: 'DELETE',
        success: function(response) {
          closeDeleteModal();
          if (response.success) {
            showToast({
              eleWrapper: '#dbclient-toaster',
              msg: response.message || 'Column deleted successfully',
              theme: 'success',
              closeButton: true,
              autoClose: true
            });
            setTimeout(() => {
              location.reload();
            }, 1000);
          } else {
            showToast({
              eleWrapper: '#dbclient-toaster',
              msg: response.error || 'Failed to delete column',
              theme: 'error',
              closeButton: true,
              autoClose: true
            });
          }
        },
        error: function(xhr) {
          closeDeleteModal();
          const error = xhr.responseJSON?.error || 'Failed to delete column';
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: error,
            theme: 'error',
            closeButton: true,
            autoClose: true
          });
        }
      });
    }
  }

  // Handle DELETE input validation
  $('#deleteConfirmInput').on('input', function() {
    const input = $(this);
    let value = input.val().toUpperCase();
    input.val(value); // Force uppercase
    value = value.trim();
    const confirmBtn = $('#confirmDeleteBtn');
    const hint = $('#deleteConfirmHint');

    if (value === 'DELETE') {
      confirmBtn.prop('disabled', false);
      confirmBtn.css('opacity', '1');
      hint.html('<span style="color: #16a34a;">✓ Ready to delete</span>');
      input.css('border-color', '#16a34a');
    } else if (value.length > 0) {
      confirmBtn.prop('disabled', true);
      confirmBtn.css('opacity', '0.5');
      hint.html('<span style="color: #dc2626;">Incorrect. Type "DELETE" to proceed</span>');
      input.css('border-color', '#dc2626');
    } else {
      confirmBtn.prop('disabled', true);
      confirmBtn.css('opacity', '0.5');
      hint.html('You must type exactly "DELETE" to proceed');
      input.css('border-color', '#d1d5db');
    }
  });

  // Allow Enter key to submit when DELETE is typed
  $('#deleteConfirmInput').on('keypress', function(e) {
    if (e.which === 13 && $(this).val().toUpperCase().trim() === 'DELETE') {
      executeDelete();
    }
  });

  // Close delete modal on outside click
  document.getElementById('deleteConfirmModal').addEventListener('click', function(e) {
    if (e.target === this) {
      closeDeleteModal();
    }
  });


  function closeModal() {
    document.getElementById('rowModal').classList.remove('active');
  }

  $('#rowForm').on('submit', function(e) {
    e.preventDefault();

    const formData = {};
    columns.forEach(function(column) {
      const fieldId = 'field_' + column.replace(/[^a-zA-Z0-9_]/g, '_');
      const fieldElement = document.getElementById(fieldId);
      if (fieldElement) {
        const value = fieldElement.value.trim();
        if (value !== '') {
          formData[column] = value;
        }
      }
    });

    const rowIdValue = document.getElementById('rowId').value;
    const encodedRowId = encodeURIComponent(rowIdValue);
    const url = isEditMode ?
      '/dbclient/table/' + tableName + '/' + encodedRowId + '/update' :
      '/dbclient/table/' + tableName + '/insert';

    const method = isEditMode ? 'PUT' : 'POST';

    $.ajax({
      url: url,
      type: method,
      data: formData,
      success: function(response) {
        if (response.success) {
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: response.message || (isEditMode ? 'Row updated successfully' : 'Row added successfully'),
            theme: 'success',
            closeButton: true,
            autoClose: true
          });
          closeModal();
          loadTableData(currentPage, searchTerm); // Reload current page
        } else {
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: response.error || 'Operation failed',
            theme: 'error',
            closeButton: true,
            autoClose: true
          });
        }
      },
      error: function(xhr) {
        const error = xhr.responseJSON?.error || 'Operation failed';
        showToast({
          eleWrapper: '#dbclient-toaster',
          msg: error,
          theme: 'error',
          closeButton: true,
          autoClose: true
        });
      }
    });
  });

  // Close modal on outside click
  document.getElementById('rowModal').addEventListener('click', function(e) {
    if (e.target === this) {
      closeModal();
    }
  });

  // Column Management Functions
  let isEditColumnMode = false;

  function openAddColumnModal() {
    isEditColumnMode = false;
    document.getElementById('columnModalTitle').textContent = 'Add Column';
    document.getElementById('columnForm').reset();
    document.getElementById('columnNameOriginal').value = '';
    document.getElementById('columnName').disabled = false;
    document.getElementById('afterColumnGroup').style.display = 'block';
    document.getElementById('columnModal').classList.add('active');
  }

  function editColumn(columnName, columnType, nullable, defaultValue) {
    isEditColumnMode = true;
    document.getElementById('columnModalTitle').textContent = 'Edit Column: ' + columnName;
    document.getElementById('columnName').value = columnName;
    document.getElementById('columnName').disabled = true;
    document.getElementById('columnNameOriginal').value = columnName;

    // Set column type
    const typeSelect = document.getElementById('columnType');
    const customInput = document.getElementById('columnTypeCustom');
    const option = Array.from(typeSelect.options).find(opt => opt.value === columnType);
    if (option) {
      typeSelect.value = columnType;
      customInput.value = '';
    } else {
      typeSelect.value = '';
      customInput.value = columnType;
    }

    document.getElementById('columnNullable').checked = nullable === 'YES';
    document.getElementById('columnDefault').value = defaultValue || '';
    document.getElementById('afterColumnGroup').style.display = 'none';
    document.getElementById('columnModal').classList.add('active');
  }


  function closeColumnModal() {
    document.getElementById('columnModal').classList.remove('active');
  }

  $('#columnForm').on('submit', function(e) {
    e.preventDefault();

    const columnName = document.getElementById('columnName').value.trim();
    const columnTypeCustom = document.getElementById('columnTypeCustom').value.trim();
    const columnType = columnTypeCustom || document.getElementById('columnType').value;
    const nullable = document.getElementById('columnNullable').checked;
    const defaultValue = document.getElementById('columnDefault').value.trim();
    const afterColumn = document.getElementById('afterColumn').value;

    if (!columnName || !columnType) {
      showToast({
        eleWrapper: '#dbclient-toaster',
        msg: 'Column name and type are required',
        theme: 'warning',
        closeButton: true,
        autoClose: true
      });
      return;
    }

    const formData = {
      column_name: columnName,
      column_type: columnType,
      nullable: nullable ? 'YES' : 'NO',
      default_value: defaultValue,
      after_column: afterColumn
    };

    let url, method;
    if (isEditColumnMode) {
      url = '/dbclient/table/' + tableName + '/column/' + encodeURIComponent(columnName) + '/update';
      method = 'PUT';
      delete formData.column_name; // Don't send column name for update
      delete formData.after_column; // Don't send after_column for update
    } else {
      url = '/dbclient/table/' + tableName + '/column/add';
      method = 'POST';
    }

    $.ajax({
      url: url,
      type: method,
      data: formData,
      success: function(response) {
        if (response.success) {
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: response.message || (isEditColumnMode ? 'Column updated successfully' : 'Column added successfully'),
            theme: 'success',
            closeButton: true,
            autoClose: true
          });
          closeColumnModal();
          setTimeout(() => {
            location.reload();
          }, 1000);
        } else {
          showToast({
            eleWrapper: '#dbclient-toaster',
            msg: response.error || 'Operation failed',
            theme: 'error',
            closeButton: true,
            autoClose: true
          });
        }
      },
      error: function(xhr) {
        const error = xhr.responseJSON?.error || 'Operation failed';
        showToast({
          eleWrapper: '#dbclient-toaster',
          msg: error,
          theme: 'error',
          closeButton: true,
          autoClose: true
        });
      }
    });
  });

  // Toggle between select and custom input
  $('#columnType').on('change', function() {
    if ($(this).val()) {
      $('#columnTypeCustom').val('');
    }
  });

  $('#columnTypeCustom').on('input', function() {
    if ($(this).val()) {
      $('#columnType').val('');
    }
  });

  // Close column modal on outside click
  document.getElementById('columnModal').addEventListener('click', function(e) {
    if (e.target === this) {
      closeColumnModal();
    }
  });
</script>
@endpush